# Generated by Django 3.1.2 on 2022-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('nickName', models.TextField()),
                ('address', models.TextField(null=True)),
                ('tel', models.TextField(null=True)),
                ('sex', models.IntegerField()),
                ('birthday', models.DateField()),
                ('name', models.TextField(null=True)),
                ('corpId', models.PositiveBigIntegerField(null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
