import { User } from "@entities";
import { Avatar, IconButton, Stack } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FC, ReactNode } from "react";
import styles from "../styles/Layout.module.scss";
import PostAddIcon from "@mui/icons-material/PostAdd";
import { Button } from "@mui/material";
const Layout: FC<{ children: ReactNode; title: string; auth: User | null }> = ({ children, title, auth }) => {
  const TopButton = () =>
    auth ? (
      <Stack direction={"row"} spacing={1} alignItems="center">
        <Link passHref={true} href="/post/new">
          <IconButton>
            <PostAddIcon />
          </IconButton>
        </Link>
        <Avatar alt={auth.nickName} sx={{ height: 30, width: 30 }} />
      </Stack>
    ) : (
      <Link passHref={true} href={"/login"}>
        <a className={styles.loginButton}>LOGIN</a>
      </Link>
    );
  return (
    <>
      <header className={styles.header}>
        <Link passHref={true} href={"/"}>
          <Image className={styles.logo} src="/logo.svg" alt="Devtree" width={180} height={20} />
        </Link>
        <TopButton />
      </header>
      <div className={styles.container}>
        <Head>
          <title>{`${title} - 데브트리 : 개발자의 지식이 모이는 곳`}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>{children}</main>
      </div>
      <footer className={styles.footer}>데브트리~~~~~</footer>
    </>
  );
};

export default Layout;
