# Generated by Django 3.1.2 on 2022-08-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220813_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='PostItem',
        ),
    ]
