import Head from "next/head";
import Image from "next/image";
import { FC, ReactNode } from "react";
import styles from "../../styles/Home.module.css";

const Layout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <>
      <header>DEVTREE</header>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>{children}</main>
      </div>
      <footer className={styles.footer}>데브트리~~~~~</footer>
    </>
  );
};

export default Layout;
