import { Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FC, ReactNode } from "react";
import styles from "../../styles/Layout.module.scss";

const Layout: FC<{ children: ReactNode; title: string }> = ({ children, title }) => {
  return (
    <>
      <header className={styles.header}>
        <Link passHref={true} href={"/"}>
          <Image className={styles.logo} src="/logo.svg" alt="Devtree" width={200} height={26} />
        </Link>
        <Link passHref={true} href={"/login"}>
          <a className={styles.loginButton}>LOGIN</a>
        </Link>
      </header>
      <div className={styles.container}>
        <Head>
          <title>{title} - 데브트리 : 개발자의 지식이 모이는 곳</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>{children}</main>
      </div>
      <footer className={styles.footer}>데브트리~~~~~</footer>
    </>
  );
};

export default Layout;
